apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  app.properties: |
    environment=production
    log.level=INFO
    api.endpoint=https://api.example.com
  database.properties: |
    db.host=localhost
    db.port=5432
    db.name=myapp
