apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: the-app
  template:
    spec:
      containers:
        - name: the-container
          image: registry/container:latest

