apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Local files
  - myNamespace.yaml
  - deployment.yaml
  - sub-dir/some-deployment.yaml

  # Local directories
  - ../nameprefix

  # Remote URLs
  - https://github.com/kubernetes-sigs/kustomize//examples/multibases/?timeout=120&ref=v3.3.1

  # Legacy hashicorp/go-getter format
  # TODO: Not found. fix it
  #- github.com/kubernets-sigs/kustomize/examples/helloWorld?ref=test-branch
  #- github.com/kubernets-sigs/kustomize/examples/helloWorld?ref=master
