apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: postgres              # image's name
    newName: my-registry/my-postgres
    newTag: v1
  - name: nginx                 # image's name
    newTag: 1.8.0
  - name: my-demo-app           # image's name
    newName: my-app
  - name: alpine                # image's name
    digest: sha256:24a0c4b4a4c0eb97a1aabb8e29f18e917d05abfe1b7a7c07857230879ce7d3d3

resources:
  - deployment.yaml